### ISSUE TITLE
Unable to start Sopel after upgrading Sopel v6.1.1 to v6.2.0 through/via Pip

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1002]
$ sopel

Welcome to Sopel. Loading modules...

Registered 42 modules,
0 modules failed to load

Connecting to ircserver:6697...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sopel/__init__.py", line 66, in run
    p.run(config.core.host, int(config.core.port))
  File "/usr/local/lib/python2.7/dist-packages/sopel/irc.py", line 154, in run
    self.initiate_connect(host, port)
  File "/usr/local/lib/python2.7/dist-packages/sopel/irc.py", line 171, in initiate_connect
    self.connect((host, port))
  File "/usr/lib/python2.7/asyncore.py", line 354, in connect
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 455, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python2.7/dist-packages/sopel/irc.py", line 224, in handle_connect
    self.write(('CAP', 'LS', '302'))
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 163, in write
    super(Sopel, self).write(args, text=None)
TypeError: must be type, not classobj

Thank you in advance. :)

**Comment by antdude** [comment]
Same with Python v3 even though it shows Python v2.7 in the errors?

sopel-python3):~$ sopel

Welcome to Sopel. Loading modules...




Registered 42 modules,
0 modules failed to load


Connecting to ircserver:6697...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sopel/__init__.py", line 66, in run
    p.run(config.core.host, int(config.core.port))
  File "/usr/local/lib/python2.7/dist-packages/sopel/irc.py", line 154, in run
    self.initiate_connect(host, port)
  File "/usr/local/lib/python2.7/dist-packages/sopel/irc.py", line 171, in initiate_connect
    self.connect((host, port))
  File "/usr/lib/python2.7/asyncore.py", line 354, in connect
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 455, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python2.7/dist-packages/sopel/irc.py", line 224, in handle_connect
    self.write(('CAP', 'LS', '302'))
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 163, in write
    super(Sopel, self).write(args, text=None)
TypeError: must be type, not classobj


$ python
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by elad661** [comment]
I think this is fixed in 6.2.1

**Comment by embolalia** [comment]
It is.

**Comment by antdude** [comment]
Thank you e* for the quick answers and fixes. Both work now with the v6.2.1 upgrade. :)
