### ISSUE TITLE
URLError: <urlopen error unknown error (_ssl.c:2826)>

### ISSUE THREAD

**Issue by Su0d** [sopel-irc/sopel#1009]
Im getting this error while running ".py" / ".w"
```
URLError: <urlopen error unknown error (_ssl.c:2826)> (file "/usr/local/lib/python2.7/urllib2.py", line 1197, in do_open)
```

Here is the traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/modules/calc.py", line 60, in py
    answer = web.get(uri + web.quote(query))
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/web.py", line 76, in get
    u = get_urllib_object(uri, timeout, headers, verify_ssl)
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/web.py", line 228, in get_urllib_object
    u = opener.open(req, None, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/web.py", line 187, in https_open
    return self.do_open(VerifiedHTTPSConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error unknown error (_ssl.c:2826)>
```

Also, while running wikipedia (.w)
im getting the same error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/modules/wikipedia.py", line 126, in wikipedia
    query = mw_search(server, query, 1)
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/modules/wikipedia.py", line 52, in mw_search
    query = json.loads(web.get(search_url))
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/web.py", line 76, in get
    u = get_urllib_object(uri, timeout, headers, verify_ssl)
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/web.py", line 228, in get_urllib_object
    u = opener.open(req, None, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/site-packages/sopel-6.2.1-py2.7.egg/sopel/web.py", line 187, in https_open
    return self.do_open(VerifiedHTTPSConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error unknown error (_ssl.c:2826)>
```

Im running Sopel v. 6.2.1 on FreeBSD 10.2, Python 2.7.11 is installed.
Python3.4 shows the same error.

**Comment by Su0d** [comment]
Fixed the issue, i'd had to point it to my CA root certificate located on the base system, in my case, /etc/ssl/cert.pem.
