### ISSUE TITLE
Configuring module chanlogs

### ISSUE THREAD

**Issue by wdm** [sopel-irc/sopel#1011]
I want to log channel messages so I whitelisted `chanlogs` module.
ConfigurationError: Channel logs are not configured

I ran `sopel --configure-modules` and it gives me this error:

[~/.sopel/modules]$ sopel --configure-modules

Configure chanlogs module (y/n)? [n]y
Configure channel logging (y/n)? [n] y
Traceback (most recent call last):
  File "/usr/local/bin/sopel", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/sopel/run_script.py", line 111, in main
    _wizard('mod', opts.config)
  File "/usr/local/lib/python2.7/dist-packages/sopel/config/__init__.py", line 227, in _wizard
    config._modules()
  File "/usr/local/lib/python2.7/dist-packages/sopel/config/__init__.py", line 211, in _modules
    module.configure(self)
  File "/usr/local/lib/python2.7/dist-packages/sopel_modules/chanlogs/__init__.py", line 39, in configure
    config.interactive_add(
  File "/usr/local/lib/python2.7/dist-packages/sopel/config/__init__.py", line 167, in __getattr__
    % (type(self).__name__, name))
AttributeError: 'Config' object has no attribute 'interactive_add'

**Comment by maxpowa** [comment]
This should be fixed in the latest code from https://github.com/sopel-irc/sopel-chanlogs . If you have any further problems, please create them on that issue tracker. sopel-chanlogs is no longer shipped with the default install.
