### ISSUE TITLE
.reload * kills the bot

### ISSUE THREAD

**Issue by neonobjclash** [sopel-irc/sopel#1048]
When I issue the .reload command to Sopel, it throws the error
```
AttributeError: can't set attribute (file "/usr/local/lib/python3.4/dist-packages/sopel/bot.py", line 397, in __setattr__)
```
...and becomes unresponsive.

From stderr:
```
Traceback (most recent call last):
  File "/home/caleb/sopel/sopel/bot.py", line 442, in call
    exit_code = func(sopel, trigger)
  File "/home/caleb/sopel/sopel/modules/reload.py", line 125, in pm_f_reload
    f_reload(bot, trigger)
  File "/home/caleb/sopel/sopel/modules/reload.py", line 38, in f_reload
    bot.command_groups = collections.defaultdict(list)
  File "/home/caleb/sopel/sopel/bot.py", line 398, in __setattr__
    return setattr(self._bot, attr, value)
AttributeError: can't set attribute
```

This happens from the both the git version and pip3 installed version (v. 6.3.1).
I was able to reproduce the issue on my Arch machine as well as my Debian server. Meicceli from the #Sopel channel was also able to reproduce the issue.

**Comment by maxpowa** [comment]
Thanks
