### ISSUE TITLE
youtube.py intermittently failing 

### ISSUE THREAD

**Issue by reverieeee** [sopel-irc/sopel#1060]
hey guys,

got an issue where sopel's youtube module is intermittently failing- sopel was installed via pip, and seems to be bailing on ssl.py when parsing youtube links:

`FreeBSD host.na.me 10.2-RELEASE-p14 FreeBSD 10.2-RELEASE-p14 #0: Wed Mar 16 20:46:12 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64`

```
Traceback (most recent call last):
  File "/home/sopel/.local/lib/python2.7/site-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/usr/home/sopel/.sopel/extra/sopel-youtube/sopel_modules/youtube/youtube.py", line 83, in get_info
    _say_result(bot, trigger, match.group(2), include_link=False)
  File "/usr/home/sopel/.sopel/extra/sopel-youtube/sopel_modules/youtube/youtube.py", line 89, in _say_result
    part='snippet,contentDetails,statistics',
  File "/home/sopel/.local/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/sopel/.local/lib/python2.7/site-packages/googleapiclient/http.py", line 755, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/sopel/.local/lib/python2.7/site-packages/googleapiclient/http.py", line 93, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/sopel/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/sopel/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/sopel/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1307, in _conn_request
    response = conn.getresponse()
  File "/usr/local/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/local/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
error: [Errno 54] Connection reset by peer
```

```
Sopel v. 6.3.1
```

this is usually (temporarily) solved by restarting sopel. i have the following in `default.cfg`:

`ca_certs = /usr/local/share/certs/ca-root-nss.crt`

**Comment by reverieeee** [comment]
woops, just realized this should be an issue under the sopel-youtube repo. my bad!
