### ISSUE TITLE
VersionConflict dist-packages requests 2.2.1 & requests>=2.3.0

### ISSUE THREAD

**Issue by mossarelli** [sopel-irc/sopel#1068]
Running Mint 17.3 on client and Ubuntu server 14 or 15 on the server.

I install Sopel using the installation instructions. I tested Python3 2 months ago and had the same issue, now using Python2.7 and getting the same issue.

```
Successfully installed sopel xmltodict pytz praw pyenchant pygeoip backports.ssl-match-hostname update-checker decorator six

$ sopel
Traceback (most recent call last):
  File "/usr/local/bin/sopel", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (requests 2.2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.3.0'))
```

I've spent hours upon hours googling every single traceback call, updating, upgrading python modules from install backports.ssl_match_hostname, praw, pillow. This issue have not been fixed on the main branch for over two months.

Is sopel requesting 2.2.1 of dist-packages or >2.3.0?

You need to make the installation instructions more inclusive. There's issues in both Python2.7 and Python3 when trying to run the bot and when the bot finally gets going you get unicode errors. Don't get me started on the cygwin version.

I'm going to compile from latest stable source to see if I can get a working version.

**Comment by mossarelli** [comment]
Update: requests is a python package. 10 Internet currencies for naming convention.
