### ISSUE TITLE
Problem with .weather

### ISSUE THREAD

**Issue by morpheusbeing** [sopel-irc/sopel#1076]
New user and new to python, On Debian Testing latest, python 2.7.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python2.7/dist-packages/sopel/modules/weather.py", line 144, in weather
    location = parsed.get('channel').get('title')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by dgw** [comment]
Duplicate of #1029 and/or #1050; should be fixed in #1058, which will be included in the next release (ping @embolalia for timeline).

**Comment by morpheusbeing** [comment]
Thank you very much.
