### ISSUE TITLE
Encountering a traceback when attempting to start Sopel

### ISSUE THREAD

**Issue by ghostfreeman** [sopel-irc/sopel#1089]
When trying to start Sopel on Ubuntu 14.04.1 from pip, I get the follow error and then it closes gracefully

```
Traceback (most recent call last):
  File "/usr/local/bin/sopel", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (requests 2.2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.3.0'))
```

There is no log directory created, presumably because it crashes before it can touch those records.

Below is the install logs from pip

```
Downloading/unpacking sopel
  Downloading sopel-6.3.1.tar.gz (107kB): 107kB downloaded
  Running setup.py (path:/tmp/pip_build_root/sopel/setup.py) egg_info for package sopel
    
Downloading/unpacking xmltodict (from sopel)
  Downloading xmltodict-0.10.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/xmltodict/setup.py) egg_info for package xmltodict
    
Downloading/unpacking pytz (from sopel)
  Downloading pytz-2016.4-py2.py3-none-any.whl (480kB): 480kB downloaded
Downloading/unpacking praw (from sopel)
  Downloading praw-3.5.0-py2.py3-none-any.whl (69kB): 69kB downloaded
Downloading/unpacking pyenchant (from sopel)
  Downloading pyenchant-1.6.6-py2.py3-none-any.whl (60kB): 60kB downloaded
Downloading/unpacking pygeoip (from sopel)
  Downloading pygeoip-0.3.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from sopel)
Downloading/unpacking backports.ssl-match-hostname (from sopel)
  Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname
    
Downloading/unpacking update-checker==0.11 (from praw->sopel)
  Downloading update_checker-0.11-py2.py3-none-any.whl
Downloading/unpacking decorator>=4.0.9,<4.1 (from praw->sopel)
  Downloading decorator-4.0.10-py2.py3-none-any.whl
Downloading/unpacking six==1.10 (from praw->sopel)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: sopel, xmltodict, pytz, praw, pyenchant, pygeoip, backports.ssl-match-hostname, update-checker, decorator, six
  Running setup.py install for sopel
    
    Installing sopel script to /usr/local/bin
  Running setup.py install for xmltodict
    
  Running setup.py install for backports.ssl-match-hostname
    
  Found existing installation: six 1.5.2
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed sopel xmltodict pytz praw pyenchant pygeoip backports.ssl-match-hostname update-checker decorator six
Cleaning up...
```

**Comment by dgw** [comment]
````
pkg_resources.VersionConflict: (requests 2.2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.3.0'))
````

````
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from sopel)
````

There's your problem.

**Comment by FabriceFABS** [comment]
Sorry to up this topic.
I really don't know exactly how to avoid this issue.
Would you be kind to explain it to me exactly ?
