### ISSUE TITLE
KeyError: Identifier

### ISSUE THREAD

**Issue by rinzes** [sopel-irc/sopel#1131]
Traceback (most recent call last):
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/coretasks.py", line 377, in track_quit
    channel.clear_user(trigger.nick)
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/tools/target.py", line 65, in clear_user
    user = self.users[nick]
KeyError: Identifier('Afkbio')

**Comment by maxpowa** [comment]
Pull the latest git version of sopel, was fixed in 20eda29542a2b6d495f601d3af88b9848121888b .

**Comment by rinzes** [comment]
I orginally installed using pip and it's says I am already up to date. Not sure how to use sopel if I install using git.

**Comment by maxpowa** [comment]
```
pip install git+https://github.com/sopel-irc/sopel.git@master
```

**Comment by rinzes** [comment]
Thanks
