### ISSUE TITLE
KeyError: Identifier('pt')

### ISSUE THREAD

**Issue by rinzes** [sopel-irc/sopel#1139]
Traceback (most recent call last):
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/coretasks.py", line 377, in track_quit
    channel.clear_user(trigger.nick)
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/tools/target.py", line 65, in clear_user
    user = self.users[nick]
KeyError: Identifier('pt')

**Comment by dgw** [comment]
Sopel version? I believe this is fixed in 6.4.0. See #1005, #1014, and #1131.

**Comment by rinzes** [comment]
That was 6.3.1.. I've ugraded to 6.4.0 and will see what happens
