### ISSUE TITLE
https error from a subdirectory on a url

### ISSUE THREAD

**Issue by tylerhoot** [sopel-irc/sopel#1221]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sopel-6.5.0-py3.5.egg/sopel/bot.py", line 470, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python3.5/dist-packages/sopel-6.5.0-py3.5.egg/sopel/modules/url.py", line 130, in title_auto
    results = process_urls(bot, trigger, urls)
  File "/usr/local/lib/python3.5/dist-packages/sopel-6.5.0-py3.5.egg/sopel/modules/url.py", line 158, in process_urls
    matched = check_callbacks(bot, trigger, url, False)
  File "/usr/local/lib/python3.5/dist-packages/sopel-6.5.0-py3.5.egg/sopel/modules/url.py", line 182, in check_callbacks
    function(bot, trigger, match)
  File "/usr/local/lib/python3.5/dist-packages/sopel-6.5.0-py3.5.egg/sopel/module.py", line 389, in helper
    return function(bot, trigger, match)
  File "/usr/local/lib/python3.5/dist-packages/sopel-6.5.0-py3.5.egg/sopel/modules/xkcd.py", line 124, in get_url
    numbered_result(bot, int(match.group(1)), latest)
TypeError: numbered_result() missing 1 required positional argument: 'verify_ssl'

ERROR:sopel.modules.sopel.irc:Exception from #purgatory: TypeError: numbered_result() missing 1 required positional argument: 'verify_ssl' (file "/usr/local/lib/python3.5/dist-packages/sopel-6.5.0-py3.5.egg/sopel/modules/xkcd.py", line 124, in get_url) (:tchoot!tchoot@swizzie-2b5.ra1.7nmpml.IP PRIVMSG #purgatory :https://xkcd.com/705)
```

**Comment by tylerhoot** [comment]
its a old bug that NO one pushed the fix in to the release build yet...
#1118

**Comment by antdude** [comment]
Still no fix? :(
