### ISSUE TITLE
reload: error with plugin whose file has moved

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1761]
```
[2019-11-23 01:33:33,719] sopel.bot            INFO     - Unloaded plugin reddit
[2019-11-23 01:33:33,720] sopel.bot            ERROR    - Unexpected error ([Errno 2] No such file or directory: '/var/lib/sopel/modules/reddit.py') from dgw at 2019-11-23 01:33:33.719968. Message was: Kaede: reload reddit
Traceback (most recent call last):
  File "/home/dgw/sopel-dev/sopel/bot.py", line 533, in call
    exit_code = func(sopel, trigger)
  File "/home/dgw/sopel-dev/sopel/module.py", line 567, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/home/dgw/sopel-dev/sopel/modules/reload.py", line 48, in f_reload
    bot.reload_plugin(name)
  File "/home/dgw/sopel-dev/sopel/bot.py", line 257, in reload_plugin
    plugin.reload()
  File "/home/dgw/sopel-dev/sopel/plugins/handlers.py", line 370, in reload
    self._module = self._load()
  File "/home/dgw/sopel-dev/sopel/plugins/handlers.py", line 342, in _load
    with open(self.path) as mod:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/sopel/modules/reddit.py'
```

Note that immediately saying `Kaede: load reddit` worked just fine. Clearly the plugin system can adapt, but maybe there's a race condition?

I've only seen this with a single-file plugin, but that's only because my Sopel bot doesn't have any directory-based plugins (I avoid writing them because of other known reloading problems). Presumably it affects any plugin, if the type changes (e.g. from a file in `.sopel/modules` to a submodule in `sopel.modules.*`)? Needs more testing, though preferably not at almost 01:00 local time. 😁

Assigning to the crazy Frenchman who wrote the new plugin handlers, since he'll be able to figure out where to start debugging faster than anyone else. 😛

**Comment by dgw** [comment]
Punted, per IRC. This will allow time for Exirel to develop a better solution, without starting with a kludge first.

**Comment by Exirel** [comment]
Months later, and I'm still not sure how to fix that exactly.

**Comment by Exirel** [comment]
Yup, year later, still no idea how to approach that properly.

**Comment by dgw** [comment]
Let's revisit this after we drop old Python crap for 8.0. If enough EOL Python versions go away, this might be simpler.

**Comment by dgw** [comment]
Here again from the future, musing that #1695 is kind of related.

**Comment by dgw** [comment]
Going along with the other plugin-related wishlist stuff. Not sure when this might get worked on, but it remains a wishlist item and I would like to look at it again after 8.0.
