### ISSUE TITLE
irc: trying to join timeout scheduler thread when timeout occurs is a bad idea

### ISSUE THREAD

**Issue by Exirel** [sopel-irc/sopel#1821]
### Description

To check for timeout, there is a job manager (`timeout_scheduler`) with a job that runs `_check_timeout`. When this job detect a timeout, it calls `backend.handle_close`, which tries to join the job manager thread.

This is a problem, because in that case, it tries to join itself, and that is not allowed.

A hotfix (see #1820) has been submitted and approved for 7.0.1, and now it's time to come with a proper solution that makes the problem to disapear in 7.1.0.

### Reproduction steps

See logs.

### Expected behavior

1. the bot shouldn't tries to join the timeout scheduler thread within itself
2. a proper cleanup must be performed in any case

### Logs

```
[2020-03-13 15:43:36,014] sopel.irc.backends   ERROR    - Server timeout detected after 147s; closing.
[2020-03-13 15:43:36,014] sopel.tools.jobs     ERROR    - Error while processing job: cannot join current thread
[2020-03-13 15:43:36,015] sopel.irc.backends   ERROR    - Error with the timeout scheduler: cannot join current thread
Traceback (most recent call last):
	File "/usr/lib/python3.8/site-packages/sopel/tools/jobs.py", line 118, in _call
			job.func(self.manager)
	File "/usr/lib/python3.8/site-packages/sopel/irc/backends.py", line 60, in _check_timeout
			backend.handle_close()
	File "/usr/lib/python3.8/site-packages/sopel/irc/backends.py", line 130, in handle_close
			self.timeout_scheduler.join(timeout=15)
	File "/usr/lib/python3.8/threading.py", line 1008, in join
			raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
[2020-03-13 15:43:36,017] sopel.tools.jobs     ERROR    - Error in job scheduler: cannot join current thread
[2020-03-13 15:43:36,017] sopel.irc.backends   ERROR    - Error with the timeout scheduler: cannot join current thread
Traceback (most recent call last):
	File "/usr/lib/python3.8/site-packages/sopel/tools/jobs.py", line 118, in _call
			job.func(self.manager)
	File "/usr/lib/python3.8/site-packages/sopel/irc/backends.py", line 60, in _check_timeout
			backend.handle_close()
	File "/usr/lib/python3.8/site-packages/sopel/irc/backends.py", line 130, in handle_close
			self.timeout_scheduler.join(timeout=15)
	File "/usr/lib/python3.8/threading.py", line 1008, in join
			raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

### Environment

- Sopel `.version`: 7.0.0

### Notes

My thanks to @alligatorme who discovered that issue and published the hotfix.

**Comment by Exirel** [comment]
Actually, closed by #1890 because I figured that we don't need to join this thread. It's all fine!
