### ISSUE TITLE
My sopel doesn't reconnect after losing Internet connection.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1860]
### Description
My Sopel, named URL, doesn't reconnect after losing Internet connection.

### Reproduction steps
1. Connect my Sopel/URL bot to an IRC server and join multiple channels.
2. Wait for an Internet disconnection.
3. Internet reconnects.
4. My bot is missing and not even shown in 12 years old, updated 64-bit Debian Jessie v8 box's memory anymore.

### Expected behavior
My Sopel/URL bot should reconnect without any issues without (exit/crash?)ing even if there's a SSL. Rbot and my IRC clients always reconnected when retrying multiple times even if SSL connections failed.

### Logs
```
$ cat default.error.log
[2020-05-09 06:40:03,146] sopel.irc.backends   ERROR    - Server timeout detected after 180s; closing.
[2020-05-09 06:40:54,474] sopel.bot            ERROR    - Error in imdb setup: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/bot.py", line 213, in setup_plugins
    plugin.setup(self)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/plugins/handlers.py", line 256, in setup
    self._module.setup(bot)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel_modules/imdb/imdb.py", line 37, in setup
    if not bot.memory.contains('url_callbacks'):
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/tools/__init__.py", line 348, in deprecated_func
    stderr(text)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/tools/__init__.py", line 560, in stderr
    print(string, file=sys.stderr)
OSError: [Errno 5] Input/output error
[2020-05-09 06:40:54,515] sopel.bot            ERROR    - Error loading habitica: invalid syntax (common.py, line 25)
Traceback (most recent call last):
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/bot.py", line 206, in setup_plugins
    plugin.load()
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/plugins/handlers.py", line 246, in load
    self._module = importlib.import_module(self.module_name)
  File "/home/ant/SopelPython3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel_modules/habitica/__init__.py", line 7, in <module>
    from .common import set_up
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel_modules/habitica/common.py", line 25
    uuid_regex = re.compile(ur'[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12}')
                                                                                      ^
SyntaxError: invalid syntax
[2020-05-09 06:40:54,530] sopel.bot            ERROR    - Error loading idlerpg: No module named 'sopel_modules.idlerpg.idlerpg'
Traceback (most recent call last):
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/bot.py", line 206, in setup_plugins
    plugin.load()
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/plugins/handlers.py", line 246, in load
    self._module = importlib.import_module(self.module_name)
  File "/home/ant/SopelPython3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel_modules/idlerpg/__init__.py", line 8, in <module>
    from .idlerpg import *
ImportError: No module named 'sopel_modules.idlerpg.idlerpg'
[2020-05-09 06:41:01,750] sopel.irc.backends   ERROR    - Connection error: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:600)
Traceback (most recent call last):
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/irc/backends.py", line 117, in initiate_connect
    self.connect((host, port))
  File "/usr/lib/python3.4/asyncore.py", line 346, in connect
    self.handle_connect_event()
  File "/usr/lib/python3.4/asyncore.py", line 448, in handle_connect_event
    self.handle_connect()
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/irc/backends.py", line 222, in handle_connect
    suppress_ragged_eofs=True)
  File "/usr/lib/python3.4/ssl.py", line 887, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:600)
```

### Environment
- Sopel `.version`: [e.g. 7.0.0 or d416e19] =  Sopel v7.0.3 (Python 3.4.2)
- Sopel installed via: [apt, pip, `setup.py install`, source, ?] = pip
- Python version: [e.g. 3.6.9] = 3.4.2 ; I use source ~/SopelPython3/bin/activate command.
- Operating system: [e.g. Debian 10] = Debian Jessie v8
- IRCd `/version`: [e.g. InspIRCd 3.0.1]  = ircd-ratbox-3.0.8(20121231_3-27427).
- Relevant plugins: [adminchannel, weather, custom\_thing.py, ?] = I use the defaults.

### Notes
No, but please feel free me to ask me if any more details if needed.

**Comment by dgw** [comment]
If Sopel reached the point of encountering an SSL protocol error, seems like it's reconnecting just fine. It _shouldn't_ proceed, and I'd argue that dropping into a retry loop if SSL/TLS doesn't work wouldn't be a good design choice.

That said, there _are_ cases in which Sopel maybe _should_ catch the exception and retry. For example, if the socket throws "no route to host" or "resource temporarily unavailable" (meaning the network connection is still down). Or maybe we retry more or less anything, but only if the connection backend has an "I _was_ connected with these settings" flag set? Thoughts from @sopel-irc/rockstars welcome here; some of you are much better at networking than I am.

(There's a lot of unrelated traceback in that log, btw. Some of your plugins are unhappy.)

**Comment by antdude** [comment]
Thanks dwg. Yeah, I have a lot of broken plugins. I assume it is because of my very old box and softwares.

**Comment by Exirel** [comment]
My bet is on a wrong port for the SSL connection. Or it might be a problem with how the server handles SSL and non-SSL connection. Either way, it might be a network/config problem rather than a code problem. Weird though.

Can you stop the process, and start it manually to see if it works from scratch?

> Relevant plugins: [adminchannel, weather, custom_thing.py, ?] = **I use the defaults.**

That is not true. (emphasis is mine)

**Comment by antdude** [comment]
I will have to wait for an Internet network outage and be there. I noticed the missing Sopel after the outage ends. What do you mean by not true?

**Comment by half-duplex** [comment]
@antdude, Is this sopel bot running in your home?

**Comment by Exirel** [comment]
> What do you mean by not true?

There are clearly some custom plugin installed, hence the error traceback such as this one:

```
[2020-05-09 06:40:54,515] sopel.bot  ERROR  - Error loading habitica: invalid syntax (common.py, line 25)
```

**Comment by antdude** [comment]
@half-duplex It's on my home connection.

@Exirel habitica wasn't part of Sopel?  Hmm, I think I need to start over with clean Sopel.

**Comment by half-duplex** [comment]
Your modem is probably acting as a captive portal when your connection is down, hijacking connections to show a "user friendly" error page. That's a complaint for your ISP. You can test this by disconnecting the phone line or coax cable from it and trying to load web pages.

If that's the case, I don't think running a bot from home with a modem that hijacks things is a use case common enough to warrant much effort to gracefully fail for. I would suggest running the bot from a systemd service or init script that can automatically restart it after a few minutes.

**Comment by antdude** [comment]
I will check it out later. I was expecting it to be like rbot since it can automatically start up in the background with its -b parameter to daemonize the rbot.

**Comment by antdude** [comment]
> My bet is on a wrong port for the SSL connection. Or it might be a problem with how the server handles SSL and non-SSL connection. Either way, it might be a network/config problem rather than a code problem. Weird though.

SSL port is 6697 (verify_ssl=off in my ~/.sopel/default.cfg). I know sometimes my friend's private IRC server (ircd-ratbox-3.0.8 and using 64-bit Fedora v31 -- I could invite privately to test it with your Sopel bot(s)). It sometimes doesn't connect and have to be retried several times. It would be great if Sopel can keep retrying like rbot does.

 
> Can you stop the process, and start it manually to see if it works from scratch?

Do you mean during the disconnection? I just had another one that lasted a few minutes. Sopel process wasn't running again from it and after my cable Internet came back.

**Comment by HumorBaby** [comment]
I know this may sound odd, but make sure that you have the latest CA certificates (e.g., `ca‑certificates` package for Ubuntu) on your system (or upgrade your python `certifi` package if you use that approach).

<br/>
<details><summary>This part of the error:</summary>
<p>

```[2020-05-09 06:41:01,750] sopel.irc.backends   ERROR    - Connection error: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:600)
Traceback (most recent call last):
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/irc/backends.py", line 117, in initiate_connect
    self.connect((host, port))
  File "/usr/lib/python3.4/asyncore.py", line 346, in connect
    self.handle_connect_event()
  File "/usr/lib/python3.4/asyncore.py", line 448, in handle_connect_event
    self.handle_connect()
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/irc/backends.py", line 222, in handle_connect
    suppress_ragged_eofs=True)
  File "/usr/lib/python3.4/ssl.py", line 887, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:600)
```
</p>
</details>

is reminiscent of similar issues I've seen/had due to newer certificates dropping support for older SSL versions (thus leading to protocol and handshake errors if you have out of date root CA certs).


Not completely sure why such an issue would manifest only on reconnection though :shrug: but I figured I'd suggest it… worst case, your root certs are now up-to-date :smile_cat:

**Comment by antdude** [comment]
I assume my both Python's Pip ca-certificates and 64-bit Debian Jessie v8 are too old in this 12 years old PC:

$ apt-cache show ca-certificates
Package: ca-certificates
Version: 20141019+deb8u4
Installed-Size: 419
Maintainer: Michael Shuler <michael@pbandjelly.org>
Architecture: all
Depends: openssl (>= 1.0.0), debconf (>= 0.5) | debconf-2.0
Breaks: ca-certificates-java (<< 20121112+nmu1)
Description-en: Common CA certificates
 This package includes PEM files of CA certificates to allow SSL-based
 applications to check for the authenticity of SSL connections.
 .
 It includes, among others, certificate authorities used by the Debian
 infrastructure and those shipped with Mozilla's browsers.
 .
 Please note that Debian can neither confirm nor deny whether the
 certificate authorities whose certificates are included in this package
 have in any way been audited for trustworthiness or RFC 3647 compliance.
 Full responsibility to assess them belongs to the local system
 administrator.
Description-md5: 085a1b1af3f2d16012dfc750cd9aedc8
Enhances: openssl
Multi-Arch: foreign
Section: misc
Priority: optional
Filename: pool/updates/main/c/ca-certificates/ca-certificates_20141019+deb8u4_all.deb
Size: 185432
MD5sum: 9bbfae9d2b23d12709a0246a1f255ddc
SHA1: 43f4ed2fd1470328cfb992200f4a59e40c5671ae
SHA256: df55d3ec4f25868d367471411be80a3a117d152419f505068893bfc0f76fa817

Package: ca-certificates
Version: 20141019+deb8u3
Installed-Size: 367
Maintainer: Michael Shuler <michael@pbandjelly.org>
Architecture: all
Depends: openssl (>= 1.0.0), debconf (>= 0.5) | debconf-2.0
Enhances: openssl
Breaks: ca-certificates-java (<< 20121112+nmu1)
Description-en: Common CA certificates
 This package includes PEM files of CA certificates to allow SSL-based
 applications to check for the authenticity of SSL connections.
 .
 It includes, among others, certificate authorities used by the Debian
 infrastructure and those shipped with Mozilla's browsers.
 .
 Please note that Debian can neither confirm nor deny whether the
 certificate authorities whose certificates are included in this package
 have in any way been audited for trustworthiness or RFC 3647 compliance.
 Full responsibility to assess them belongs to the local system
 administrator.
Description-md5: 085a1b1af3f2d16012dfc750cd9aedc8
Multi-Arch: foreign
Tag: protocol::ssl, role::app-data, security::authentication
Section: misc
Priority: optional
Filename: pool/main/c/ca-certificates/ca-certificates_20141019+deb8u3_all.deb
Size: 206870
MD5sum: f39a638adcc521e82fcfc802be156cf2
SHA1: 4926838b39306aa467005b355e2cef55723b890f
SHA256: bd799f47f5ae3260b6402b1fe19fe2c37f2f4125afcd19327bf69a9cf436aeff

$ sudo apt-get install ca-certificates
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


$ pip install certifi
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Requirement already satisfied: certifi in /home/ant/SopelPython3/lib/python3.4/site-packages (2020.4.5.1)

**Comment by dgw** [comment]
Closing as stale and not reproducible by any of the core devs. It really does sound like an environment problem, not a Sopel bug.
