### ISSUE TITLE
Unexpected error (get) from .announce

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel#2040]
### Description
.announce fatals with unexpected error (get)

### Reproduction steps
1. Upgrade to latest master
2. Connect to server, join a few channels
3. Use .announce
4. Check your logs

### Expected behavior
No fatals, it works 

### Logs
```
[2021-03-14 16:02:42,710] sopel.bot            ERROR    - Unexpected error (get) from RhinosF1 at 2021-03-14 16:02:42.710332. Message was: .announce this is a test --rf1
Traceback (most recent call last):
  File "/srv/sopelbots/devvenv/lib/python3.7/site-packages/sopel/bot.py", line 698, in call_rule
    rule.execute(sopel, trigger)
  File "/srv/sopelbots/devvenv/lib/python3.7/site-packages/sopel/plugins/rules.py", line 996, in execute
    exit_code = self._handler(bot, trigger)
  File "/srv/sopelbots/devvenv/lib/python3.7/site-packages/sopel/plugin.py", line 914, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/srv/sopelbots/devvenv/lib/python3.7/site-packages/sopel/modules/announce.py", line 37, in announce
    size = bot.isupport.get('TARGMAX', {}).get('PRIVMSG', 1)
  File "/srv/sopelbots/devvenv/lib/python3.7/site-packages/sopel/irc/isupport.py", line 192, in __getattr__
    raise AttributeError(name)
AttributeError: get
```

### Environment
- Sopel `.version`: latest master
- Sopel installed via: build our own wheel using build & then pip install
- Python version: 3.7.3
- Operating system: Debian Buster
- IRCd `/version`: ircd-seven-1.1.9(20191023-4b033a7b9221,charybdis-3.4-dev). egan.freenode.net
- Relevant plugins: announce

### Notes
Anything else we should know?

**Comment by Exirel** [comment]
Instead of `bot.issuport.get` to check if a config value is available, an `if hasattr(bot.isupposrt, '...')` block must be used. That's a fairly easy fix.

**Comment by dgw** [comment]
@Exirel Is there a good reason not to give `bot.isupport` a `get()` method? It already kind of pretends to be a dict via supporting subscripting and I think the `in` operator. Might as well ape that part too.

**Comment by Exirel** [comment]
Something something reason. 🙃 

I don't have a better answer right now. Might have a look at this.
