### ISSUE TITLE
find_updates: Unexpected error (local variable 'info' referenced before assignment)

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel#2051]
### Description
An error is logged, errors shouldn't happen.

### Reproduction steps
Seen in log channel, unknown, run the bot for long enough???

### Expected behavior
No error

### Logs
```
[2021-03-31 22:00:24,531] sopel.tools.jobs     ERROR    - Error while processing job: local variable 'info' referenced before assignment
[2021-03-31 22:00:24,538] sopel.bot            ERROR    - Unexpected error (local variable 'info' referenced before assignment)
Traceback (most recent call last):
  File "/srv/sopelbots/devvenv/lib/python3.7/site-packages/sopel/tools/jobs.py", line 191, in _call
    job.execute(self.manager)
  File "/srv/sopelbots/devvenv/lib/python3.7/site-packages/sopel/tools/jobs.py", line 463, in execute
    return self._handler(manager)
  File "/srv/sopelbots/devvenv/lib/python3.7/site-packages/sopel/modules/find_updates.py", line 86, in check_version
    latest = info['version']
UnboundLocalError: local variable 'info' referenced before assignment

```

### Environment
- Sopel `.version`: https://github.com/sopel-irc/sopel/commit/96c55aff852bf40bca56de49b2bc30378bf1c819
- Sopel installed via: pip/wheel
- Python version: 3.7.3
- Operating system: Debian 10.9
- IRCd `/version`: freenode
- Relevant plugins: find_updates

**Comment by dgw** [comment]
Smells like a logic error in the error-handling code from #1779 (sorry). Reaching that reference to `info` without the variable having been assigned yet tells me execution is being allowed to continue too far in the failure state.
