### ISSUE TITLE
.search command shows "Unexpected error (Exceeded 30 redirects.)..."

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#2402]
### Description

[07:11pm] <BetaAnt> .search ants
07:11PM <URL> Unexpected error (Exceeded 30 redirects.) from BetaAnt at
          2023-01-22 03:11:10.990658. Message was: .search ants
[07:11pm] <BetaAnt> .version
07:11PM <URL> [version] Sopel v7.1.9 | Python: 3.11.1

It used to work before today.

### Reproduction steps

Type .search keyword and see its results.

### Expected behavior

.search should show me a non-error result and not fail with "Unexpected error (Exceeded 30 redirects.)..." error.

### Relevant logs

```shell
$ ./sopel -d
Sopel 7.1.9 (running on Python 3.11.1)
https://sopel.chat/

Loaded config file: /home/ant/.sopel/default.cfg
sopel.bot            INFO     - Loading plugins...
[2023-01-21 19:10:56,303] sopel.bot            INFO     - Plugin loaded: pronouns
[2023-01-21 19:10:56,306] sopel.bot            INFO     - Plugin loaded: tell
[2023-01-21 19:10:56,310] sopel.bot            INFO     - Plugin loaded: remind
[2023-01-21 19:10:56,312] sopel.bot            INFO     - Plugin loaded: invite
[2023-01-21 19:10:56,314] sopel.bot            INFO     - Plugin loaded: find
[2023-01-21 19:10:56,324] sopel.bot            INFO     - Plugin loaded: admin
[2023-01-21 19:10:56,475] sopel.bot            INFO     - Plugin loaded: ip
[2023-01-21 19:10:56,477] sopel.bot            INFO     - Plugin loaded: ping
[2023-01-21 19:10:56,478] sopel.modules.safety INFO     - Downloading malicious domain list from https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2023-01-21 19:10:57,168] sopel.bot            INFO     - Plugin loaded: safety
[2023-01-21 19:10:57,181] sopel.bot            INFO     - Plugin loaded: reload
[2023-01-21 19:10:57,182] sopel.bot            INFO     - Plugin loaded: choose
[2023-01-21 19:10:57,187] sopel.bot            INFO     - Plugin loaded: meetbot
[2023-01-21 19:10:57,195] sopel.bot            INFO     - Plugin loaded: emoticons
[2023-01-21 19:10:57,196] sopel.bot            INFO     - Plugin loaded: rand
[2023-01-21 19:10:57,197] sopel.bot            INFO     - Plugin loaded: countdown
[2023-01-21 19:10:57,198] sopel.bot            INFO     - Plugin loaded: wiktionary
[2023-01-21 19:10:57,201] sopel.bot            INFO     - Plugin loaded: wikipedia
[2023-01-21 19:10:57,347] sopel.bot            INFO     - Plugin loaded: reddit
[2023-01-21 19:10:57,401] sopel.bot            INFO     - Plugin loaded: tld
[2023-01-21 19:10:57,403] sopel.bot            INFO     - Plugin loaded: version
[2023-01-21 19:10:57,408] sopel.bot            INFO     - Plugin loaded: units
[2023-01-21 19:10:57,409] sopel.bot            INFO     - Plugin loaded: seen
[2023-01-21 19:10:57,410] sopel.bot            INFO     - Plugin loaded: lmgtfy
[2023-01-21 19:10:57,412] sopel.bot            INFO     - Plugin loaded: calc
[2023-01-21 19:10:57,419] sopel.bot            INFO     - Plugin loaded: clock
[2023-01-21 19:10:57,472] sopel.bot            ERROR    - Cannot register URL callback: Bugzilla URL callback requires "bugzilla.domains" to be configured; check your config file.
[2023-01-21 19:10:57,472] sopel.bot            INFO     - Plugin loaded: bugzilla
[2023-01-21 19:10:57,473] sopel.bot            INFO     - Plugin loaded: find_updates
[2023-01-21 19:10:57,475] sopel.bot            INFO     - Plugin loaded: xkcd
[2023-01-21 19:10:57,478] sopel.bot            INFO     - Plugin loaded: search
[2023-01-21 19:10:57,481] sopel.bot            INFO     - Plugin loaded: url
[2023-01-21 19:10:57,482] sopel.bot            ERROR    - Error in help setup: global flags not at the start of the expression at position 10
Traceback (most recent call last):
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 337, in setup_plugins
    plugin.register(self)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/handlers.py", line 330, in register
    bot.add_plugin(self, *relevant_parts)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 479, in add_plugin
    self.register_callables(callables)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 620, in register_callables
    rule = plugin_rules.Rule.from_callable(settings, callbl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 815, in from_callable
    regexes = cls.regex_from_callable(settings, handler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 791, in regex_from_callable
    return tuple(_clean_rules(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 87, in _clean_rules
    yield _compile_pattern(pattern, nick, aliases)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 106, in _compile_pattern
    return re.compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 10
[2023-01-21 19:10:57,525] sopel.bot            INFO     - Plugin loaded: py
[2023-01-21 19:10:57,528] sopel.bot            INFO     - Plugin loaded: translate
[2023-01-21 19:10:57,538] sopel.bot            INFO     - Plugin loaded: adminchannel
[2023-01-21 19:10:57,553] sopel.bot            INFO     - Plugin loaded: dice
[2023-01-21 19:10:57,555] sopel.bot            INFO     - Plugin loaded: announce
[2023-01-21 19:10:57,556] sopel.bot            INFO     - Plugin loaded: uptime
[2023-01-21 19:10:57,558] sopel.bot            INFO     - Plugin loaded: isup
[2023-01-21 19:10:57,559] sopel.bot            INFO     - Plugin loaded: unicode_info
[2023-01-21 19:10:57,561] sopel.bot            INFO     - Plugin loaded: currency
[2023-01-21 19:10:57,575] sopel.bot            INFO     - Plugin loaded: coretasks
[2023-01-21 19:10:57,575] sopel.bot            INFO     - Registered 39 plugins, 1 failed, 0 disabled
[2023-01-21 19:10:57,577] sopel.irc.backends   INFO     - Connecting to irc.zimage.com:6697...
[2023-01-21 19:10:57,591] sopel.irc.backends   INFO     - Connection accepted by the server...
[2023-01-21 19:10:57,591] sopel.irc            INFO     - Connected, initiating setup sequence
[2023-01-21 19:10:57,605] sopel.coretasks      INFO     - Client capability negotiation list: multi-prefix
[2023-01-21 19:10:57,605] sopel.coretasks      INFO     - End of client capability negotiation requests.
[2023-01-21 19:11:04,491] sopel.coretasks      INFO     - Joining 1 channels (with JOIN throttle OFF); this may take a moment.
[2023-01-21 19:11:04,492] sopel.coretasks      INFO     - No custom command to execute.
[2023-01-21 19:11:04,493] sopel.coretasks      INFO     - Received RPL_MYINFO from server: URL, irc1.zimage.com, ircd-ratbox-3.0.8
[2023-01-21 19:11:04,534] sopel.coretasks      INFO     - Channel joined: #linux
[2023-01-21 19:11:04,535] sopel.coretasks      INFO     - Channel's topic updated: #linux
[2023-01-21 19:11:04,538] sopel.coretasks      INFO     - Channel joined: #bots
[2023-01-21 19:11:04,539] sopel.coretasks      INFO     - Channel joined: #games
[2023-01-21 19:11:04,541] sopel.coretasks      INFO     - Channel joined: #videogaming
[2023-01-21 19:11:04,543] sopel.coretasks      INFO     - Channel joined: #pulsar
[2023-01-21 19:11:04,544] sopel.coretasks      INFO     - Updated mode for channel: #linux
[2023-01-21 19:11:04,556] sopel.coretasks      INFO     - Updated mode for channel: #bots
[2023-01-21 19:11:04,561] sopel.coretasks      INFO     - Updated mode for channel: #games
[2023-01-21 19:11:04,566] sopel.coretasks      INFO     - Updated mode for channel: #videogaming
[2023-01-21 19:11:04,574] sopel.coretasks      INFO     - Updated mode for channel: #pulsar
[2023-01-21 19:11:10,990] sopel.bot            ERROR    - Unexpected error (Exceeded 30 redirects.) from BetaAnt at 2023-01-22 03:11:10.990658. Message was: .search ants
Traceback (most recent call last):
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 763, in call_rule
    rule.execute(sopel, trigger)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 1057, in execute
    exit_code = self._handler(bot, trigger)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/modules/search.py", line 157, in search
    bu = bing_search(query) or '-'
         ^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/modules/search.py", line 35, in bing_search
    response = requests.get(base, parameters, headers=header_spoof)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

### Sopel version

7.1.9

### Installation method

`pip install`

### Python version

3.11.1

### Operating system

Fedora v37

### IRCd

rcd-ratbox-3.0.8(20121231_3-27427)

### Relevant plugins

defaults

**Comment by dgw** [comment]
Can't reproduce. Checking commit history, no meaningful code changes have occurred in `search.py` between 7.1.x and current master. Likely to be caused by interference from something between your bot and the internet. Captive portal Wi-Fi?

**Comment by antdude** [comment]
The server isn't on wifi. It uses FIOS and network cables.  Maybe more logs will help?

$ pwd
/home/ant/.sopel/logs

$ ls -all
total 48
drwx------. 2 ant ant 20480 Jan 21 23:32 .
drwx------. 4 ant ant  4096 Jan 21 23:33 ..
-rw-r--r--. 1 ant ant  4752 Jan 21 23:33 default.error.log
-rw-r--r--. 1 ant ant     0 Jan 21 23:32 default.exceptions.log
-rw-r--r--. 1 ant ant     0 Jan 21 23:32 default.raw.log
-rw-r--r--. 1 ant ant  9948 Jan 21 23:33 default.sopel.log

$ cat default.error.log
[2023-01-21 23:32:43,089] sopel.bot            ERROR    - Cannot register URL callback: Bugzilla URL callback requires "bugzilla.domains" to be configured; check your config file.
[2023-01-21 23:32:43,121] sopel.bot            ERROR    - Error in help setup: global flags not at the start of the expression at position 10
Traceback (most recent call last):
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 337, in setup_plugins
    plugin.register(self)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/handlers.py", line 330, in register
    bot.add_plugin(self, *relevant_parts)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 479, in add_plugin
    self.register_callables(callables)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 620, in register_callables
    rule = plugin_rules.Rule.from_callable(settings, callbl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 815, in from_callable
    regexes = cls.regex_from_callable(settings, handler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 791, in regex_from_callable
    return tuple(_clean_rules(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 87, in _clean_rules
    yield _compile_pattern(pattern, nick, aliases)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 106, in _compile_pattern
    return re.compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 10
[2023-01-21 23:33:02,660] sopel.bot            ERROR    - Unexpected error (Exceeded 30 redirects.) from BetaAnt at 2023-01-22 07:33:02.660819. Message was: .search ants
Traceback (most recent call last):
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 763, in call_rule
    rule.execute(sopel, trigger)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 1057, in execute
    exit_code = self._handler(bot, trigger)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/modules/search.py", line 157, in search
    bu = bing_search(query) or '-'
         ^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/modules/search.py", line 35, in bing_search
    response = requests.get(base, parameters, headers=header_spoof)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

$ cat default.sopel.log
[2023-01-21 23:32:40,833] sopel.bot            INFO     - Loading plugins...
[2023-01-21 23:32:41,574] sopel.bot            INFO     - Plugin loaded: pronouns
[2023-01-21 23:32:41,599] sopel.bot            INFO     - Plugin loaded: tell
[2023-01-21 23:32:41,615] sopel.bot            INFO     - Plugin loaded: remind
[2023-01-21 23:32:41,616] sopel.bot            INFO     - Plugin loaded: invite
[2023-01-21 23:32:41,619] sopel.bot            INFO     - Plugin loaded: find
[2023-01-21 23:32:41,631] sopel.bot            INFO     - Plugin loaded: admin
[2023-01-21 23:32:41,785] sopel.bot            INFO     - Plugin loaded: ip
[2023-01-21 23:32:41,787] sopel.bot            INFO     - Plugin loaded: ping
[2023-01-21 23:32:41,984] sopel.bot            INFO     - Plugin loaded: safety
[2023-01-21 23:32:41,997] sopel.bot            INFO     - Plugin loaded: reload
[2023-01-21 23:32:41,998] sopel.bot            INFO     - Plugin loaded: choose
[2023-01-21 23:32:42,004] sopel.bot            INFO     - Plugin loaded: meetbot
[2023-01-21 23:32:42,025] sopel.bot            INFO     - Plugin loaded: emoticons
[2023-01-21 23:32:42,026] sopel.bot            INFO     - Plugin loaded: rand
[2023-01-21 23:32:42,026] sopel.bot            INFO     - Plugin loaded: countdown
[2023-01-21 23:32:42,028] sopel.bot            INFO     - Plugin loaded: wiktionary
[2023-01-21 23:32:42,031] sopel.bot            INFO     - Plugin loaded: wikipedia
[2023-01-21 23:32:42,466] sopel.bot            INFO     - Plugin loaded: reddit
[2023-01-21 23:32:42,792] sopel.bot            INFO     - Plugin loaded: tld
[2023-01-21 23:32:42,946] sopel.bot            INFO     - Plugin loaded: version
[2023-01-21 23:32:42,950] sopel.bot            INFO     - Plugin loaded: units
[2023-01-21 23:32:42,979] sopel.bot            INFO     - Plugin loaded: seen
[2023-01-21 23:32:42,980] sopel.bot            INFO     - Plugin loaded: lmgtfy
[2023-01-21 23:32:42,982] sopel.bot            INFO     - Plugin loaded: calc
[2023-01-21 23:32:42,988] sopel.bot            INFO     - Plugin loaded: clock
[2023-01-21 23:32:43,089] sopel.bot            ERROR    - Cannot register URL callback: Bugzilla URL callback requires "bugzilla.domains" to be configured; check your config file.
[2023-01-21 23:32:43,090] sopel.bot            INFO     - Plugin loaded: bugzilla
[2023-01-21 23:32:43,105] sopel.bot            INFO     - Plugin loaded: find_updates
[2023-01-21 23:32:43,114] sopel.bot            INFO     - Plugin loaded: xkcd
[2023-01-21 23:32:43,117] sopel.bot            INFO     - Plugin loaded: search
[2023-01-21 23:32:43,120] sopel.bot            INFO     - Plugin loaded: url
[2023-01-21 23:32:43,121] sopel.bot            ERROR    - Error in help setup: global flags not at the start of the expression at position 10
Traceback (most recent call last):
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 337, in setup_plugins
    plugin.register(self)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/handlers.py", line 330, in register
    bot.add_plugin(self, *relevant_parts)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 479, in add_plugin
    self.register_callables(callables)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 620, in register_callables
    rule = plugin_rules.Rule.from_callable(settings, callbl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 815, in from_callable
    regexes = cls.regex_from_callable(settings, handler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 791, in regex_from_callable
    return tuple(_clean_rules(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 87, in _clean_rules
    yield _compile_pattern(pattern, nick, aliases)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 106, in _compile_pattern
    return re.compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 10
[2023-01-21 23:32:43,232] sopel.bot            INFO     - Plugin loaded: py
[2023-01-21 23:32:43,262] sopel.bot            INFO     - Plugin loaded: translate
[2023-01-21 23:32:43,272] sopel.bot            INFO     - Plugin loaded: adminchannel
[2023-01-21 23:32:43,288] sopel.bot            INFO     - Plugin loaded: dice
[2023-01-21 23:32:43,290] sopel.bot            INFO     - Plugin loaded: announce
[2023-01-21 23:32:43,291] sopel.bot            INFO     - Plugin loaded: uptime
[2023-01-21 23:32:43,298] sopel.bot            INFO     - Plugin loaded: isup
[2023-01-21 23:32:43,299] sopel.bot            INFO     - Plugin loaded: unicode_info
[2023-01-21 23:32:43,307] sopel.bot            INFO     - Plugin loaded: currency
[2023-01-21 23:32:43,322] sopel.bot            INFO     - Plugin loaded: coretasks
[2023-01-21 23:32:43,322] sopel.bot            INFO     - Registered 39 plugins, 1 failed, 0 disabled
[2023-01-21 23:32:43,324] sopel.irc.backends   INFO     - Connecting to irc.zimage.com:6697...
[2023-01-21 23:32:47,428] sopel.irc.backends   INFO     - Connection accepted by the server...
[2023-01-21 23:32:47,429] sopel.irc            INFO     - Connected, initiating setup sequence
[2023-01-21 23:32:47,451] sopel.coretasks      INFO     - Client capability negotiation list: multi-prefix
[2023-01-21 23:32:47,451] sopel.coretasks      INFO     - End of client capability negotiation requests.
[2023-01-21 23:32:53,491] sopel.coretasks      INFO     - Joining 1 channels (with JOIN throttle OFF); this may take a moment.
[2023-01-21 23:32:53,492] sopel.coretasks      INFO     - No custom command to execute.
[2023-01-21 23:32:53,494] sopel.coretasks      INFO     - Received RPL_MYINFO from server: URL, irc1.zimage.com, ircd-ratbox-3.0.8
[2023-01-21 23:32:53,544] sopel.coretasks      INFO     - Channel joined: #linux
[2023-01-21 23:32:53,546] sopel.coretasks      INFO     - Channel's topic updated: #linux
[2023-01-21 23:32:53,548] sopel.coretasks      INFO     - Channel joined: #bots
[2023-01-21 23:32:53,550] sopel.coretasks      INFO     - Channel joined: #games
[2023-01-21 23:32:53,552] sopel.coretasks      INFO     - Channel joined: #videogaming
[2023-01-21 23:32:53,554] sopel.coretasks      INFO     - Channel joined: #pulsar
[2023-01-21 23:32:53,556] sopel.coretasks      INFO     - Updated mode for channel: #linux
[2023-01-21 23:32:53,566] sopel.coretasks      INFO     - Updated mode for channel: #bots
[2023-01-21 23:32:53,571] sopel.coretasks      INFO     - Updated mode for channel: #games
[2023-01-21 23:32:53,575] sopel.coretasks      INFO     - Updated mode for channel: #videogaming
[2023-01-21 23:32:53,579] sopel.coretasks      INFO     - Updated mode for channel: #pulsar
[2023-01-21 23:33:02,660] sopel.bot            ERROR    - Unexpected error (Exceeded 30 redirects.) from BetaAnt at 2023-01-22 07:33:02.660819. Message was: .search ants
Traceback (most recent call last):
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/bot.py", line 763, in call_rule
    rule.execute(sopel, trigger)
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/plugins/rules.py", line 1057, in execute
    exit_code = self._handler(bot, trigger)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/modules/search.py", line 157, in search
    bu = bing_search(query) or '-'
         ^^^^^^^^^^^^^^^^^^
  File "/home/ant/.local/lib/python3.11/site-packages/sopel/modules/search.py", line 35, in bing_search
    response = requests.get(base, parameters, headers=header_spoof)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by dgw** [comment]
A captive Wi-Fi portal was just one idea. Sometimes ISPs intercept browser traffic if there is an urgent account matter that needs attention. If their stuff is set up incorrectly (or just unusually), it can lead to redirect loops.

Could also be that Bing (the search engine that the plugin checks first, and which is triggering the exception) has decided it doesn't like your IP range for some reason, but it's set up wrong or sends a redirection that's not handled properly by `requests`.

Those "more logs" are basically the same output again, so no, it doesn't help. While there's no debug logging in the `search` plugin that you could turn on, this issue is clearly between your server and its ISP, or between your server and Bing. The code raising an error is in `requests`, not in Sopel, and the same feature works fine on both test instances I have tried.

Sorry I can't be more helpful, but there is no more debugging I can think of to try without having access to your host/bot.

(Downgrading Python will fix the `help` plugin failing to load, an error seen in the extra logs. One of its handlers uses a pattern that's no longer allowed in 3.11. See #2403.)

**Comment by antdude** [comment]
Thanks, dgw. Is it possible to see this URL without Sopel to see what it looks like in a text web browser (lynx, eLinks, etc.) since I SSH2 into my friend's Fedora box?

**Comment by dgw** [comment]
You can try. It's built here; the `lang` parameter is currently always `en-US`:

https://github.com/sopel-irc/sopel/blob/81b5e1180f2ac331263894323b7c52c8f7ab9825/sopel/modules/search.py#L30-L35

So you'll want to test something like `https://www.bing.com/search?mkt=en-US&q=ants`

Always a chance your browser will show something completely different, of course. Big services like Bing use all kinds of little signals to decide whether they should service a request, not all of which you can easily control.

**Comment by antdude** [comment]
Lynx redirects me to Using https://cn.bing.com/search?mkt=en-US&q=ants in a loop. Huh? Why is it going to china?

CN 
Looking up cn.bing.com.
Making HTTPS connection to cn.bing.comg =(
SSL callback:ok, preverify_ok=1, ssl_okay=0
SSL callback:ok, preverify_ok=1, ssl_okay=0x(+nt)]
SSL callback:ok, preverify_ok=1, ssl_okay=0                         [U:a:S:b:h]
Verified connection to cn.bing.com (subj=*.bing.com)
Certificate issued by: /C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 02
Secure 256-bit TLSv1.2 (ECDHE-RSA-AES256-GCM-SHA384) HTTP connection
Sending HTTP request.
HTTP request sent; waiting for response.
HTTP/1.1 301 Moved Permanently
Data transfer complete
HTTP/1.1 301 Moved Permanently
Using https://www.bing.com/?mkt=en-US&q=ants&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN
Looking up www.bing.com
Making HTTPS connection to www.bing.com
SSL callback:ok, preverify_ok=1, ssl_okay=0
SSL callback:ok, preverify_ok=1, ssl_okay=0
SSL callback:ok, preverify_ok=1, ssl_okay=0
Verified connection to www.bing.com (cert=www.bing.com)
Certificate issued by: /C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 02
Secure 256-bit TLSv1.2 (ECDHE-RSA-AES256-GCM-SHA384) HTTP connection
Sending HTTP request.
HTTP request sent; waiting for response.
HTTP/1.1 302 Found
Data transfer complete
HTTP/1.1 302 Found
Using https://cn.bing.com/?mkt=en-US&q=ants&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN

lynx: Can't access startfile https://www.bing.com/search?mkt=en-US&q=ants

**Comment by antdude** [comment]
Weird. I am going to have to contact my friend about this since he owns this server and ISP.
