### ISSUE TITLE
[Core]Connecting with SSL when CA Certs are unavailable needs better error message

### ISSUE THREAD

**Issue by tyrope** [sopel-irc/sopel#570]
Found by @Connor22

```
Could not open CA certificates file. SSL will not work properly.
Could not open CA certificates file. SSL will not work properly.

Welcome to Willie. Loading modules...
[snip]
Registered 33 modules,
9 modules failed to load


Connecting to irc.twitch.tv:6667...
Connection error: [Errno 2] No such file or directory
```

**Comment by dgw** [comment]
@tpltnt You recently submitted a TLS-related PR, so would you mind giving this a look at some point?

**Comment by tpltnt** [comment]
I am using the following configuration:
```
[core]
nick = Sopel
host = irc.twitch.tv
use_ssl = true
port = 6697
owner = foo
channels = #test
```
Running sopel yields:
```
./sopel.py               

Welcome to Sopel. Loading modules...




Registered 42 modules,
0 modules failed to load


Connecting to irc.twitch.tv:6697...
Invalid certficate, hostname mismatch!
Traceback (most recent call last):
  File "/home/foobar/code/sopel/sopel/irc.py", line 215, in handle_connect
    ssl.match_hostname(self.ssl.getpeercert(), self.config.core.host)
  File "/usr/lib/python3.5/ssl.py", line 305, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'irc.twitch.tv' doesn't match either of '*.chat.twitch.tv', 'chat.twitch.tv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foobar/code/sopel/sopel/__init__.py", line 81, in run
    p.run(config.core.host, int(config.core.port))
  File "/home/foobar/code/sopel/sopel/irc.py", line 155, in run
    self.initiate_connect(host, port)
  File "/home/foobar/code/sopel/sopel/irc.py", line 171, in initiate_connect
    self.connect((host, port))
  File "/usr/lib/python3.5/asyncore.py", line 341, in connect
    self.handle_connect_event()
  File "/usr/lib/python3.5/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/home/foobar/code/sopel/sopel/irc.py", line 218, in handle_connect
    os.unlink(self.config.core.pid_file_path)
AttributeError: 'CoreSection' object has no attribute 'pid_file_path'
```
It looks like a configuration problem since the (configured) hostname `irc.twitch.tv` is an alias for `irc.chat.twitch.tv`, which (technically) should match the `*.chat.twitch.tv` wildcard.

See:
 ```% dig irc.twitch.tv

; <<>> DiG 9.10.3-P4-Debian <<>> irc.twitch.tv
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45251
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;irc.twitch.tv.			IN	A

;; ANSWER SECTION:
irc.twitch.tv.		600	IN	CNAME	irc.chat.twitch.tv.
irc.chat.twitch.tv.	300	IN	CNAME	irc-production-388322493.us-west-2.elb.amazonaws.com.
irc-production-388322493.us-west-2.elb.amazonaws.com. 300 IN A 52.11.199.45
irc-production-388322493.us-west-2.elb.amazonaws.com. 300 IN A 35.163.17.216
irc-production-388322493.us-west-2.elb.amazonaws.com. 300 IN A 35.164.90.161
irc-production-388322493.us-west-2.elb.amazonaws.com. 300 IN A 34.211.57.21
irc-production-388322493.us-west-2.elb.amazonaws.com. 300 IN A 52.27.133.22
irc-production-388322493.us-west-2.elb.amazonaws.com. 300 IN A 52.41.113.12

;; AUTHORITY SECTION:
us-west-2.elb.amazonaws.com. 428 IN	NS	ns-1475.awsdns-56.org.
us-west-2.elb.amazonaws.com. 428 IN	NS	ns-1769.awsdns-29.co.uk.
us-west-2.elb.amazonaws.com. 428 IN	NS	ns-332.awsdns-41.com.
us-west-2.elb.amazonaws.com. 428 IN	NS	ns-560.awsdns-06.net.

;; Query time: 95 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Sat Mar 24 00:14:26 CET 2018
;; MSG SIZE  rcvd: 364
```

**Comment by dgw** [comment]
Thanks, @tpltnt. Between the hostname, the port (OP says 6667, which is supposed to be plaintext not SSL), and the config error, I'm going to close this as both old/outdated and probably invalid/user-error.
