### ISSUE TITLE
How to create a Willie() object ???

### ISSUE THREAD

**Issue by texom512** [sopel-irc/sopel#805]
Hello,

I want to create Willie object for send a message like this:
> import willie.bot
bot = willie.bot.Willie()
bot.say('Hello world!',  '#channel')
but of course that return an error:
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.3/dist-packages/willie/bot.py", line 49, in __init__
    irc.Bot.__init__(self, config.core)
AttributeError: 'NoneType' object has no attribute 'core'

So how can I send a message on a specific channel without decorators?

Thanks in advance!

**Comment by tyrope** [comment]
It looks like you are trying to use Willie without actually using Willie core.

The real question you should be asking yourself is: "Why do I not want to use decorators?"

**Comment by embolalia** [comment]
I'm assuming what you're trying to do is send a message to a channel as a one-off thing in the middle of a script doing other things? Willie is built to be long-running, and none of what it does accounts for this kind of situation. If you do what it looks like you're trying to do, you'll also run into issues not knowing when the bot is actually ready to send, and figuring out how to wait on the message to have actually sent before killing the bot. If you really want to send a message from a different process through Willie, the best way is to run the bot in the normal way, and then write a module to utilize the IPC method of your choice (sockets, inotify, task queue, whatever) to listen for the message and send it.

**Comment by elad661** [comment]
This has been needinfo since May with no activity from the original reporter. Closing. Feel free to re-open if you can provide the requested information.
