### ISSUE TITLE
Seen module won't work

### ISSUE THREAD

**Issue by coquelicot00** [sopel-irc/sopel#857]
Hello,
I set sopel to recognize "!" as the command prefix and typed "!seen." This was the response I got:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0a4-py3.4.egg/sopel/bot                                         .py", line 245, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0a4-py3.4.egg/sopel/mod                                     ules/seen.py", line 33, in seen
    trigger.sender)
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0a4-py3.4.egg/sopel/too                                         ls/time.py", line 93, in get_timezone
    if not tz and config and config.has_option('core', 'default_timezone'):
  File "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0a4-py3.4.egg/sopel/con                                         fig/__init__.py", line 163, in __getattr__
    % (type(self).__name__, name))
AttributeError: 'Config' object has no attribute 'has_option'

Any help would be greatly appreciated as I love this bot already and desperately want it to function properly.

EDIT: Even weirder,
user: !seen Data
Data: Sorry, I haven't seen Data around.
user: !seen user
Data: AttributeError: 'Config' object has no attribute 'has_option' (file "/usr/local/lib/python3.4/dist-packages/sopel-6.0.0a4-py3.4.egg/sopel/config/__init__.py", line 163, in __getattr__)

**Comment by coquelicot00** [comment]
Apologies - I had accidentally submitted this post without the full logs. It has been edited to include them.

**Comment by embolalia** [comment]
Do you still get this on 6.0.0a5? It should be fixed.

**Comment by coquelicot00** [comment]
Works just fine on the newest. Thank you!
