### ISSUE TITLE
Issue with resolving Wikipedia links.

### ISSUE THREAD

**Issue by therealscottcarlow** [sopel-irc/sopel#875]
I've been playing a little bit of whack-a-mole with issues. First I set up my time format for linux while running the bot on Windows, so I fixed that in the config using:
```
default_time_format
```
Then I started having SSL issues, so I created cacerts.pem and no longer had SSL issues. But now Wikipedia links won't resolve. Here's the traceback:
```
Traceback (most recent call last):
  File "c:\python34\lib\urllib\request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "c:\python34\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "c:\python34\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "c:\python34\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "c:\python34\lib\http\client.py", line 857, in send
    self.connect()
  File "c:\python34\lib\http\client.py", line 834, in connect
    self.timeout, self.source_address)
  File "c:\python34\lib\socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "c:\python34\lib\socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\sopel\bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "c:\python34\lib\site-packages\sopel\modules\wikipedia.py", line 131, in wikipedia
    query = mw_search(server, query, 1)
  File "c:\python34\lib\site-packages\sopel\modules\wikipedia.py", line 57, in mw_search
    query = json.loads(web.get(search_url))
  File "c:\python34\lib\site-packages\sopel\web.py", line 74, in get
    u = get_urllib_object(uri, timeout, headers, verify_ssl)
  File "c:\python34\lib\site-packages\sopel\web.py", line 225, in get_urllib_object
    u = opener.open(req, None, timeout)
  File "c:\python34\lib\urllib\request.py", line 463, in open
    response = self._open(req, data)
  File "c:\python34\lib\urllib\request.py", line 481, in _open
    '_open', req)
  File "c:\python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "c:\python34\lib\urllib\request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\python34\lib\urllib\request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

Any idea as to why? I tried looking through your documentation before submitting this issue, but I don't see anything that particularly helps in this case. Can someone reproduce this on a Windows machine? I'm going to spin up sopel on Arch and see how that runs.

UPDATE: Fresh install of latest version of sopel from pip on Arch, no changes past initial config. Can't resolve Wikipedia links. Traceback is different, though. I'm running Arch through a VM and can't exactly copy/paste, so I apologize for posting a screenshot instead.

![](http://puu.sh/k0OeA/01ab498443.png)

**Comment by dgw** [comment]
The only person I know who runs sopel on Windows is @WeiZs1. Maybe he's figured out something?

**Comment by therealscottcarlow** [comment]
It's not confined to windows. Running into the same exact issue on Arch.

**Comment by embolalia** [comment]
What is the URL you're giving? Can you get to that URL in a browser? (It kinda sounds like a DNS issue from the error message…)

**Comment by therealscottcarlow** [comment]
If you use .wiki <args> in channel sopel returns that error. It also won't resolve valid wikipedia links pasted into the channel.

**Comment by embolalia** [comment]
Looks like I forgot to put a default in for the language config value. I was getting a different error, though, so try yours against the latest master and see if it works.

**Comment by embolalia** [comment]
No replies since the commit was pushed a few months ago, so I'm going to assume this is resolved.
