### ISSUE TITLE
Sopel 6.0b0 install

### ISSUE THREAD

**Issue by rinzes** [sopel-irc/sopel#884]
Installing Sopel 6.0.0b0 using pip I get the following error:

File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging

AttributeError: 'module' object has no attribute 'packaging'

**Comment by rinzes** [comment]
Here is the traceback on manual install

p/sopel-6.0.0b0# python setup.py
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from setuptools import setup
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python2.7/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'

**Comment by embolalia** [comment]
Looks like this is pypa/pip#2679. Looks like the solution is `apt-get install python-pip` and/or `pip uninstall distribute`. It also looks like it works in virtualenv, at least for me, and doesn't seem to affect Fedora derivatives. Either way, it seems to be a pip and/or Debian issue, so there's nothing we can do about it here.
