### ISSUE TITLE
sopel.py run failure due to missing arguments in configure/types.py

### ISSUE THREAD

**Issue by PythonJedi** [sopel-irc/sopel#939]
I want to fix an unrelated issue I noticed, but in doing so, I found that I couldn't run sopel.py from the latest commit:

```
$ python3 sopel.py
Welcome to Sopel!
I can't seem to find the configuration file, so let's generate it!

Please answer the following questions to create your configuration file:

Encountered an error while writing the config file. This shouldn't happen. Check permissions.
Traceback (most recent call last):
  File "sopel.py", line 6, in <module>
    run_script.main()
  File "/home/tim/projects/sopel/sopel/run_script.py", line 132, in main
    _create_config(configpath)
  File "/home/tim/projects/sopel/sopel/config/__init__.py", line 252, in _create_config
    sopel.config.core_section.configure(config)
  File "/home/tim/projects/sopel/sopel/config/core_section.py", line 24, in configure
    config.core.configure_setting('nick', 'Enter the nickname for your bot.')
  File "/home/tim/projects/sopel/sopel/config/types.py", line 95, in configure_setting
    value = clazz.configure(prompt, default, self._parent, self._section_name)
  File "/home/tim/projects/sopel/sopel/config/types.py", line 209, in configure
    return super(ValidatedAttribute, self).configure(prompt, default)
TypeError: configure() missing 2 required positional arguments: 'parent' and 'section_name'
```

When I look at the mentioned line and function definition, the function mentioned does require 4 positional arguments, but the invocation provides 2.

I'm running Void linux and Python 3.4.3

**Comment by maxpowa** [comment]
Fixed in https://github.com/sopel-irc/sopel/pull/938

**Comment by PythonJedi** [comment]
Ah, didn't see that, my bad!
