### ISSUE TITLE
.ip socket.gaierror on Sopel 6.1.1 on python 3.5.0

### ISSUE THREAD

**Issue by Phrohdoh** [sopel-irc/sopel#945]
OS X 11.10

```python
WARNING:sopel.modules.ip:Downloading GeoIP database
Traceback (most recent call last):
  File "/Users/thill/projects/python/orcabot/venv_orcabot/lib/python3.5/site-packages/sopel/bot.py", line 260, in call
    exit_code = func(sopel, trigger)
  File "/Users/thill/projects/python/orcabot/venv_orcabot/lib/python3.5/site-packages/sopel/modules/ip.py", line 118, in ip
    response += " | Location: %s" % gi_city.country_name_by_name(query)
  File "/Users/thill/projects/python/orcabot/venv_orcabot/lib/python3.5/site-packages/pygeoip/__init__.py", line 502, in country_name_by_name
    addr = self._gethostbyname(hostname)
  File "/Users/thill/projects/python/orcabot/venv_orcabot/lib/python3.5/site-packages/pygeoip/__init__.py", line 394, in _gethostbyname
    return socket.gethostbyname(hostname)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

/Users/thill/projects/python/orcabot/venv_orcabot/lib/python3.5/site-packages/sopel/bot.py:263: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/thill/.sopel/GeoLiteCity.dat'>
  self.error(trigger)
/Users/thill/projects/python/orcabot/venv_orcabot/lib/python3.5/site-packages/sopel/bot.py:263: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/thill/.sopel/GeoIPASNum.dat'>
  self.error(trigger)
```

**Comment by maxpowa** [comment]
Can you provide the ip/hostname you tried to use with .ip ?

**Comment by Phrohdoh** [comment]
`19:49 -!- Phrohdoh [~Phrohdoh@pool-71-96-95-47.dllstx.fios.verizon.net]`

**Comment by maxpowa** [comment]
Eh? You mean you did `.ip pool-71-96-95-47.dllstx.fios.verizon.net` right?

**Comment by Phrohdoh** [comment]
Hmm nope, so I bet that's the issue.
`.ip Phrohdoh`

**Comment by maxpowa** [comment]
Yeah. .ip requires a valid hostname or IP. It doesn't work with arbitrary strings or nicknames. I guess that the error could be masked better though.

**Comment by Phrohdoh** [comment]
Closing as incorrect usage of a command.
